### ISSUE TITLE
有些站点会出现 科学上网填写订阅 ，这个要怎么关闭呀？

### ISSUE THREAD

**Issue by Lovefish** [qist/tvbox#28]
没用啊，真的需要用的，自己会去设置里面填呐，干嘛要出现在资源列表里啊？每隔几部作品就有一个。

**Comment by qist** [comment]
没配置外部代理,最多是使用内部端口转发。 猫影视有个日志打印接口是外部的。那个不影响使用。

**Comment by qist** [comment]
建议使用jsm.json 这个还有是别人接口里面携带的。找到可用自行删除。

**Comment by Lovefish** [comment]
> 没配置外部代理,最多是使用内部端口转发。 猫影视有个日志打印接口是外部的。那个不影响使用。

挺影响使用的啊，打开一个分类有十个视频，平铺在电视上，要填代理的就占了一个，然后再翻一页，又占了一个，每一页都占一个。
我不知道猫影视，我就看这个hanime1

**Comment by qist** [comment]
是那个渠道的。我要去排查看看我这边ok影视没看到 我常用的就是jsm

**Comment by Lovefish** [comment]
> 是那个渠道的。我要去排查看看我这边ok影视没看到 我常用的就是jsm

ok影视
9918
hanime1
之前不会有的，好像就最近一两星期出现的

**Comment by qist** [comment]
你用的是那个json我处理一下。如果是jar的里面可能占时无法处理。

**Comment by Lovefish** [comment]
> 你用的是那个json我处理一下。如果是jar的里面可能占时无法处理。

好的谢谢。
你自己用哪一个？
好像只有这个里面才有missav和hanime1

**Comment by qist** [comment]
你说的是9918那个json么那个我可以把proxy 清理了

**Comment by Lovefish** [comment]
> 你说的是9918那个json么那个我可以把proxy 清理了

感谢

**Comment by qist** [comment]
https://qist.tycng.com/9918.json 测试看看 你是不是把json

**Comment by Lovefish** [comment]
> https://qist.tycng.com/9918.json 测试看看 你是不是把json

还有
![Uploading IMG_20240717_204737.jpg…]()

**Comment by Lovefish** [comment]
> https://qist.tycng.com/9918.json 测试看看 你是不是把json

还有
![IMG_20240717_204737](https://github.com/user-attachments/assets/d4c1c025-e978-4417-8760-7aa1d4efb2ec)

**Comment by Lovefish** [comment]
> https://qist.tycng.com/9918.json 测试看看 你是不是把json

https://github.com/qist/tvbox/raw/23a94bb412d05eed5a7ab20dda9e2dff9144e14b/9918.json
回退到这个版本，就没有代理了😂

**Comment by qist** [comment]
99188.json

**Comment by Lovefish** [comment]
> 99188.json

可以了感谢
