### ISSUE TITLE
额  好多源都崩了~

### ISSUE THREAD

**Issue by taomi** [qist/tvbox#5]
额  好多源都崩了

**Comment by qist** [comment]
是的现在guangdian 严了，不共享了。

**Comment by taomi** [comment]
> 是的现在guangdian 严了，不共享了。
看来只能自己做代理转发出来了

**Comment by taomi** [comment]
> 是的现在guangdian 严了，不共享了。

看来只能自己做代理转发出来了

**Comment by taomi** [comment]
> 是的现在guangdian 严了，不共享了。

打开IPV6来 观看了。 目前就盒子得折腾怎么开 IPV6协议

**Comment by qist** [comment]
手机 电视 有v6 就可以了

**Comment by taomi** [comment]
> 手机 电视 有v6 就可以了
开了V6后 ，才发现移动专区也是V6的
目前手头几个 EC6110T、   EC6109   比较麻烦。   得找整好V6的rom刷

**Comment by qist** [comment]
现在v6 的没任何限制的。
